# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
             users:
              jaen:
               password: jaen
               roles: 'ROLE_USER'
              admin:
               password: admin
               roles: 'ROLE_ADMIN'
    encoders:
     Symfony\Component\Security\Core\User\User: plaintext
     
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
            # activate different ways to authenticate
        my_secured_area:
             anonymous: ~
             http_basic: ~
             
    access_control:
     - { path: ^/admin, roles: ROLE_ADMIN }
 
